#!/bin/bash
# Dependencies
# npm install -g svgo chrome-webstore-manager web-ext uglifycss

this="$0"

failed() {
	set +e
	local code="$?"
	local line="$1"

	echo "=== Packaging failed ==="
	echo "Error ${code} on line ${line}:"
	echo "| $(cat "${this}" | sed $((line-2))'q;d')"
	echo "| $(cat "${this}" | sed $((line-1))'q;d')"
	echo "> $(cat "${this}" | sed $((line))'q;d')"
	echo "| $(cat "${this}" | sed $((line+1))'q;d')"
	echo "| $(cat "${this}" | sed $((line+2))'q;d')"

	exit $code
}

trap 'failed ${LINENO}' ERR

set -ue -o pipefail -o errtrace

PUSH_MOZILLA=${PUSH_MOZILLA-}
PUSH_CHROME=${PUSH_CHROME-}

pushd "$(dirname "$0")/../"

rm -rf target
mkdir -p target
mkdir -p artifact


# Add tracked files to target
git ls-tree -r master --name-only | egrep -v '^(utils/|asset/|.*\.md)' | while read FILE; do
	# Create missing directories
	if [[ "$(echo "$FILE" | grep /)" ]]; then mkdir -p "target/$(dirname "$FILE")"; fi

	cp -rp {,target/}"$FILE"
done


# Convert SVGs to data (Chrome sometimes disappears SVG assets, so we convert them into blobs)
cat toolbar.css | grep '^\s*background.*asset/.*\.svg' | sed -e 's/.*url..//g' -e 's/svg.*/svg/g' | sort -u | while read SVG; do
	sed -i '' -e "s~['\"]$SVG['\"]~$(cat "$SVG" | svgo --enable='removeViewBox,removeComments,removeUselessStrokeAndFill' -i - -o - --datauri=base64)~" target/toolbar.css
done


# Package used assets
git ls-tree -r master --name-only | egrep '\.(js|html?|css|json)' | xargs -I {} egrep "asset/[^\"']*" target/{} | sed -e "s@.*\(asset/[^\"']*\).*@\1@" | sort -u | while read ASSET; do
	mkdir -p "target/$(dirname "$ASSET")"
	cp "$ASSET" "target/$ASSET"
done


# Compress CSS
git ls-tree -r master --name-only | egrep '\.css' | xargs -I {} uglifycss --output target/{} target/{}


# Firefox
echo -e "\n\n\n========= START Firefox"
cd target
zip -r ../artifact/StumbleBar\ Firefox\ $(cat manifest.json | grep '"version"' | sed -e 's/.*: "//' -e 's/".*//').zip .
if [ "$PUSH_MOZILLA" ]; then
	# It's okay if this fails. We expect it to fail.  
	web-ext sign --api-key=$AMO_JWT_ISSUER --api-secret=$AMO_JWT_SECRET --artifacts-dir=../artifact/ || true
fi
#sed -i '' 's/\(version": "0.[0-9]*\)/\1rc1/' manifest.json
#zip -r ../artifact/StumbleBar\ Firefox\ $(cat manifest.json | grep '"version"' | sed -e 's/.*: "//' -e 's/".*//').zip .
#if [ "$PUSH_MOZILLA" ]; then
#	# It's okay if this fails. We expect it to fail.  
#	web-ext sign --api-key=$AMO_JWT_ISSUER --api-secret=$AMO_JWT_SECRET --artifacts-dir=../artifact/ || true
#fi
echo -e "========= END Firefox\n\n\n"


# Chrome
echo -e "========= START Chrome"
cd ..
cat manifest.json | pcregrep -v -M '"applications"(.|\n)*?},' > target/manifest.json
rm -rf StumbleBar
cp -rp target StumbleBar
zip -r artifact/StumbleBar\ Chrome\ $(cat manifest.json | grep '"version"' | sed -e 's/.*: "//' -e 's/".*//').zip StumbleBar
rm -rf target StumbleBar
if [ "$PUSH_CHROME" ]; then
	#WEBSTORE_TOKEN="$(chrome-webstore-manager token --client_id $WEBSTORE_CLIENT_ID --client_secret $WEBSTORE_CLIENT_SECRET)"
	WEBSTORE_TOKEN="$(chrome-webstore-manager refresh_token --client_id $WEBSTORE_CLIENT_ID --client_secret $WEBSTORE_CLIENT_SECRET --refresh_token $WEBSTORE_REFRESH_TOKEN)"
	chrome-webstore-manager update  -t $WEBSTORE_TOKEN $WEBSTORE_EXTENSION_ID "artifact/StumbleBar Chrome $(cat manifest.json | grep '"version"' | sed -e 's/.*: "//' -e 's/".*//').zip"
	chrome-webstore-manager publish -t $WEBSTORE_TOKEN $WEBSTORE_EXTENSION_ID
fi;
echo -e "========= END Chrome\n\n\n"

popd

